theme: jekyll-theme-minimal
sidebar:
  - title: "Schwartzpub Blog"
    image_alt: "image"
    text: "Welcome to my blog. I will mainly post about various projects and ideas I have while working in the IT world."