# Site settings
title: The Schwartz Pub
description: >-
  This is a space where I can post about ideas and projects I am working on, both personally and professionally.
github_username: schwartzpub
minimal_mistakes_skin: default
search: true
logo: "/assets/images/logo_red.png"
include:
  - _pages
repository: schwartzpub/schwartzpub.github.io

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author
author:
  name   : "Jacob Schwartz"
  avatar : "/assets/images/portrait.png"
  bio    : "An IT professional with over 10 years of experience in the finance industry working on a variety of infrastructure, cybersecurity, automation, and reporting solutions."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/schwartzpub"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jacob-schwartz-a9337120/"

# Footer
footer:
  links:
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/schwartzpub"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jacob-schwartz-a9337120/"

# Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: true
      comments: true
      share: false
      related: false
      sidebar:
        nav: posts
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: posts