title: The Schwartz Pub -- A Blog for IT
theme: jekyll-theme-minimal
logo: /assets/img/logo.jpg
description: This is a space where I can post about ideas and projects I am working on, both personally and professionally.